apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: gotek-build-01
spec:
  serviceAccountName: tekton
  taskRef:
    name: build-docker-image-from-git-source
  inputs:
    resources:
      - name: myproject
        resourceRef:
          name: gotek-src
    params:
      - name: pathToDockerFile
        value: /workspace/myproject/Dockerfile
      - name: pathToContext
        value: /workspace/myproject/
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: gotek-image
